# Generated by Django 4.0.4 on 2022-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sesh',
            field=models.CharField(default='01', max_length=255),
        ),
    ]
