# Generated by Django 4.0.4 on 2022-06-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_image2_product_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images')),
                ('image3', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'shoes'), ('clothing', 'clothing'), ('other', 'other'), ('gadgets', 'gadgets'), ('home-and-appliances', 'home-and-appliances'), ('accesories', 'accesories')], max_length=100),
        ),
    ]
