# Generated by Django 4.0.4 on 2022-06-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_homeslides_image1text_homeslides_image2text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslides',
            name='image1text',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='homeslides',
            name='image2text',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='homeslides',
            name='image3text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
